### ISSUE TITLE
Update hashing to Blake2b, signing to Ed25519

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/playground#32]
The [new specification](https://github.com/farcasterxyz/protocol/pull/2) requires Blake2B for hashing and Ed25519 for signing, while we currently use keccak and ECDSA.  The goal of this ticket is to: 

- [ ] Update the hashing and signing schemes in the playground
- [ ] If any special configurations are required for the scheme, specify them in the protocol

**Comment by zachterrell57** [comment]
Blake2b is not included in ethers.js so we're going to have to pull from a different library. Here is a list of some legitimate and secure dependencies and would appreciate some community input on which one seems like the best choice:

1. blakejs - https://www.npmjs.com/package/blakejs
2. blake2b - https://www.npmjs.com/package/blake2b
3. ethereum-cryptography - https://www.npmjs.com/package/ethereum-cryptography

**Comment by zachterrell57** [comment]
Ethers.js also uses secp256k1 for signing, so we will have to find another library for this too. This library is probably our best option for ed25519:
https://github.com/paulmillr/noble-ed25519

**Comment by varunsrin** [comment]
Thanks for doing the research. I think we should go with [ethereum-cryptography](https://www.npmjs.com/package/ethereum-cryptography) and [noble-ed25519](https://github.com/paulmillr/noble-ed25519) since they both have formal audits from Cure53 and are likely the most secure.
